### ISSUE TITLE
Pull the recent develop branch

### ISSUE THREAD

**Issue by hihiboss** [Nexters/Amoogye-iOS#93]
최근에 여러 개의 PR이 연속적으로 merge 되어서 develop을 업데이트 해야합니다!

따라서 `develop` 브랜치에서 `git pull origin develop` 진행해주세요.

여기까지 이상없으면 프로젝트를 빌드합니다.
> 빌드 실패하면 빌드 실패 로그 캡처해서 이슈에 올려주세요.

그 뒤, xcode 내 콘솔에 찍히는 realm path로 이동하여 `default.realm`과 `default.realm.lock` 파일을 삭제해주세요.
![image](https://user-images.githubusercontent.com/34789831/64649698-6187a180-d458-11e9-8139-d070367766d7.png)

그 다음, 시뮬레이터를 클릭하고, 상단 메뉴에서 `Hardware` - `Erase All Content and Settings`를 실행해주세요.
![image](https://user-images.githubusercontent.com/34789831/64649524-02299180-d458-11e9-8858-ac6500b4a7af.png)

다시 빌드해서 정상적으로 작동하는지 확인해주세요.

여기까지 이상없으면 됩니다.
(사실은... 없어야 합니다 ㅜㅜ 제발!!)

@tngusmiso 
빌드 성공하면 댓글 달아주세요!

**Comment by tngusmiso** [comment]
빌드가 아주아주 잘됩니다! 계량도구 추가랑 편집도 아주 잘 됩니당 :)
dim화면, new 뱃지도 잘 작동해요!
